### ISSUE TITLE
Running t/best.t takes too long

### ISSUE THREAD

**Issue by hoytech** [jgamble/Algorithm-Networksort#12]
The `best.t` test really slows down the CPAN installation.

I wonder if it's possible to do a "quick sanity check" that does a small sub-set of a full zero-one test unless the `AUTHOR_TESTING` environment variable is set, similar to how `abecedarian.t` works.

**Comment by jgamble** [comment]
At the moment, you shouldn't be running the full extent of the tests at all.

In the currently released version, the tests only go to a small value, for the sake of the testers. It's the developers who can get the long (hour+) test (believe me, I know, I had to catch a couple of errors with the new networks in #8).

I wrote my own method of handling that, but there's a standard way of separating "install" tests from "developer" tests that's either new or which I missed the first time. I'll be upgrading the Build.PL file to make use of it.

In the mean time, just don't use "build test". If you don't feel comfortable with that, use

`build test test_files=t/00-load.t`

to at least check for compilation errors.

**Comment by hoytech** [comment]
Hehe roger that on the hour+ test times...

I was just looking at master on github, good to hear it will be pared down for the CPAN release, thanks.

PS. I've considered making an Algorithm::Networksort:ZeroOne::XS module before that does this testing in parallel with optimised C code. Someday... :)
