### ISSUE TITLE
New Optimal Networks from Morwenn

### ISSUE THREAD

**Issue by jgamble** [jgamble/Algorithm-Networksort#14]
As discussed in #8, [23 and 24 -input networks](https://github.com/Morwenn/cpp-sort/wiki/Original-research#sorting-networks-23-and-24)

**Comment by jgamble** [comment]
@Morwenn With the merging of issue #6, I'm now ready to add your networks.

**Comment by jgamble** [comment]
Networks added; documentation upgraded, and changes merged into master.

Thank you.

**Comment by Morwenn** [comment]
No problem, even though they're not the best known ones :p

**Comment by jgamble** [comment]
And in case you noticed the two places where I dropped one of the 'n's in your name -- I noticed too, and they're fixed in #17.

**Comment by Morwenn** [comment]
To be honest, I thought you were trying to use 5-character names everywhere (with `badar` and `senson` around it made sense) ^^'
