### ISSUE TITLE
Final Documentation Push For 2.00

### ISSUE THREAD

**Issue by jgamble** [jgamble/Algorithm-Networksort#19]
I _think_ we're at a satisfactory point with the code. That leaves the documentation, which could stand improvement beyond the updated lists.

**Comment by jgamble** [comment]
Okay, it's done. Assuming I didn't miss anything. @Morwenn, @hoytech if there's anything I'm messing up in crediting you, please let me know.

By the way, I'm currently reserving the simple printing of the network ('print $nw;') to a grouped-style form. If that looks stupid (say, you think the formatted output should be the output and the grouped form should be via a method, let me know.

I have one item of my own -- any objection to shortening 'oddeventransposition' to  something like 'oddeventrans' or 'oddeventrpos'?

**Comment by Morwenn** [comment]
Don't worry everything looks fine :)

I fear I can't help you for the design questions though; I still know next to nothing about Perl. I tend to try to fully spell out the variable, class and function names I use too, so I'll let @hoytech and you decide on what you think is best for `oddeventransposition`.

**Comment by hoytech** [comment]
Docs look good, thanks!

I have no objections to renaming oddeventransposition, it *is* a bit of a mouthful.

**Comment by jgamble** [comment]
Okay, as of now, [Algorithm::Networksort](http://search.cpan.org/perldoc?Algorithm%3A%3ANetworksort) is up on CPAN!

Now to see what the testers think of it.

Thank you, everyone.
