### ISSUE TITLE
Rename (and Add to) Default Exports

### ISSUE THREAD

**Issue by jgamble** [jgamble/Algorithm-Networksort#20]
The exported functions from Algorithm::Networksort

- nwsrt()
- nwsrt_algorithms()

The exported functions from Algorithm::Networksort::Best

- nwsrt_best()
- nwsrt_best_names()
- nwsrt_best_title()

Yeah... I didn't consider what I was doing as far as consistency goes at all.

The plan: In Algorithm::Networksort, add an nwsrt_title() function, and rename nwsrt_algorithms() to nwsrt_names().

cc @hoytech because although I don't think enough days have gone by to catch people with this, you might be the exception.

**Comment by jgamble** [comment]
On the other hand, I may not have been as inconsistent as I thought, since the nwsrt_best() parameter is 'name =>' while the nwsrt() argument is 'algorithm =>'. I can probably make that more clear in the documents.

So we'll leave that alone. On the other hand, the missing nwsrt_title() function is a definite mistake on my part. We'll have that function for programs that need to create a selection list, while $object->title() will be used for the actual title that the object has.

**Comment by Morwenn** [comment]
Consistency is always the way to go :p

**Comment by jgamble** [comment]
Okay, this version of consistency is in and uploaded to CPAN. Yay.
