### ISSUE TITLE
algorithms which not change order of equal elements ?

### ISSUE THREAD

**Issue by p1pkin** [jgamble/Algorithm-Networksort#9]
I'm apologise, this is more question than actual issue report.
but, is there any known efficient sorting networks or algorithms, which leave equal elements in its original order ? except obvious bubble sort.

if yes, is it possible to include them in this project ?

PS: thank you for your work and researches.

**Comment by jgamble** [comment]
Hmm. It's honestly something that's never occurred to me. I did a search on "stable sort sorting networks", and didn't find much overlap (that is, stability might be found in an article, but not related to a sorting network).

Wikipedia, in its Sorting Algorithm article (https://en.wikipedia.org/wiki/Sorting_algorithm#Comparison_of_algorithms), lists both Bubble and Odd-Even sorts as stable, and they are present in a sorting network form in this module. But it's possible to destabilize a stable sort in its implementation, and I haven't tested either one for stability.

I'll keep this open, but frankly the usual way of guaranteeing an order is to extend your comparison function to handle the extra conditions.

**Comment by jgamble** [comment]
Whoops, my mistake: Odd-Even is not in the module (Batcher's other two algorithms are however, Merge-Exchange and Bitonic).

**Comment by Morwenn** [comment]
The only things I have read about stable sorting networks is that they use more comparators, or less optimal networks of the same size. For example, take a sorting network of size 3: `[[0, 2], [0, 1], [1, 2]]` is unstable; on the other hand `[[0, 1], [1, 2], [0, 1]]` is stable but trying to sort every bitstring of size 3 shows that it performs more swaps on average.

[WikiSort][1] is a stable sorting algorithm that uses sorting networks to sort subsequences whose size is lesser than or equal to 8. However, to maintain the stability, it keeps the indices of the elements and compares them when comparing equal elements. The sorting networks used aren't stable *per se*.

Anyway, there doesn't seem to be much research about stable sorting networks. Any such network will likely be the result of a suboptimal generic algorithm.

[1]: https://github.com/BonzaiThePenguin/WikiSort

**Comment by hoytech** [comment]
I believe that all so-called "transposition networks" such as bubble sort (as John said) are stable. Unfortunately they are far from ideal as the number of elements gets larger.

I suppose this is yet another parameter that finding the "best" network should be able to consider (see #8).

**Comment by p1pkin** [comment]
thanks a lot for tips and answers about stable networks.

indeed it will be nice to get "best" from stable networks list, if this is possible.

**Comment by hoytech** [comment]
This may be obvious, but you can always use a non-stable sorting algorithm to do a stable sort by modifying the values to embed the original order as a part of the value (and changing the comparison function to take this into account).

I made a simple gist to demonstrate this:

https://gist.github.com/hoytech/02a86f2e946fca4b0f0e

This is known as the [Schwartzian transform](https://en.wikipedia.org/wiki/Schwartzian_transform) and has been used to work around lack-of-stability in certain situations like in PHP scripts that only offer an unstable sort.

A related approach that might be more efficient is to create a parallel array the same size as your input, and modify the comparison function to check this array if the values in the input are equal, and modify the swap function to also swap the elements of this parallel array.

**Comment by hoytech** [comment]
@jgamble - I believe the "odd-even sort" referenced on the wikipedia page you linked is for "odd-even transposition sort", depicted here for n=8:

http://www.inf.fh-flensburg.de/lang/algorithmen/sortieren/networks/oetsen.htm

Batcher's "odd-even merge sort" is different, as depicted here for n=8:

https://en.wikipedia.org/wiki/Batcher_odd%E2%80%93even_mergesort

Batcher's O-E mergesort is an advanced algorithm but is *not* stable.

The O-E transposition sort is a primitive, almost trivial algorithm like bubble sort, but it *is* stable owing to the fact it's a transposition sort (elements are only compare-exchanged against their immediate neighbours).

Time permitting, I'm going to see if I can whip up some implementations for A::NS so we can play around with them.

**Comment by hoytech** [comment]
Odd-even transposition here:

https://github.com/jgamble/Algorithm-Networksort/pull/10

Not a great sort, but probably our best "stable" one.

I'm going to try to do Batcher's odd-even merge sort soon too...

**Comment by hoytech** [comment]
OK I'm going to stop spamming this thread after this I promise. :)

I implemented odd-even merge in this PR: https://github.com/jgamble/Algorithm-Networksort/pull/11

And I just wanted to show that this sort is not stable.

Here's how n=4 looks:

<pre>
$ algorithm-networksort-chooser --algorithm oddevenmerge --show 4
...
o--^--^--------o
   |  |         
o--v--|--^--^--o
      |  |  |   
o--^--v--|--v--o
   |     |      
o--v-----v-----o
</pre>

And here's a simple test with two numerically equal inputs:

<pre>
$ cat snstable.pl 
use strict;

use Algorithm::Networksort qw{:all};
use Data::Dumper;

my @arr = ("2 A","2 B",1,3);
my @network = nw_comparators(scalar @arr, algorithm => "oddevenmerge");

nw_sort(\@network, \@arr);

print Dumper(\@arr);
</pre>

And the output (note that `2 A` and `2 B` have been swapped):

<pre>
$ perl snstable.pl 
$VAR1 = [
          1,
          '2 B',
          '2 A',
          3
        ];
</pre>

**Comment by jgamble** [comment]
Thank you, and sorry for not responding sooner, I've been managing house guests and had little time for myself.

**Comment by hoytech** [comment]
No worries :)

**Comment by jgamble** [comment]
Closing this now. Version 2.00 is released, and if there is any chance of a stable sorting network, I suspect it will be in an addition to the Best module, not in the algorithms.
